---
title: "Lab 10"
author: "Blue Team: Matt Lawson, Nick Zimmerman "
date: "March 22, 2019"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); library(stringr)
library(dplyr)
library(lubridate)
```

```{r, message=F, warning=F}
questions <- read_csv("data/Questions_trunc.csv")
answers <- read_csv("data/Answers_trunc.csv")

questions <- questions %>% select(Id:Body)
answers <- answers %>% select(Id:Body)
```



```{r}
head(questions); head(answers)
```



## Team



### Matt

```{r}
mattq <- questions %>% mutate(ContainsCode = str_detect(Body, pattern="<code>"))
matta <- answers %>% mutate(ContainsCode = str_detect(Body, pattern="<code>"))

mattq
matta
```


### Brandon






### Nick

```{r, warning=FALSE}

Answers <- read_csv("data/Answers_trunc.csv") 
Answers <- select(Answers, -X7)
Questions <- read_csv("data/Questions_trunc.csv")
Questions <- select(Questions, -X7)

Qs <- select(Questions, Id, CreationDate)
colnames(Qs)[2] <- "QuestionDate"
Ans <- inner_join(Answers, Qs, by = c("ParentId" = "Id"))
Ans <- Ans %>% mutate(responseTime =  difftime(CreationDate,QuestionDate, units = "hours") )
Ans <- Ans %>% mutate(order = 0)

```

```{r}
ggplot(filter(Ans, responseTime > 0 & responseTime < 24))+
  geom_point(mapping = aes(responseTime,Score))
```



### Bing