---
title: "Untitled"
author: 'Blue Team: Matt Lawson,'
date: "5/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Assigning awards to MLB teams via Data Science

```{r warning=F, message=F}
columnNames <- c("Year", "League", "Wins", "Losses", "Finish", "Runs per Game", "Number of Games", "Played appearances","At bats", "Runs scored", "Hits", "Doubles", "Tripples", "Home runs", "RBIs", "Stollen bases", "Caught stealing", "Walks", "Strikeouts", "Batting average", "On base %", "Slugging %", "On base + slugging %", "Errors committed", "Double plays", "Fielding %", "Average age")


giants <- read_csv("giants.csv"); names(giants) <-  columnNames
giants <- giants %>% mutate(Team="Giants")  %>% filter(Year != 2019)

db <- read_csv("diamondbacks.csv"); names(db) <-  columnNames
db <- db %>% mutate(Team="Diamondbacks") %>% filter(Year != 2019)


dodgers <- read_csv("dodgers.csv"); names(dodgers) <-  columnNames
dodgers <- dodgers %>% mutate(Team="Dodgers") %>% filter(Year != 2019)


padres <- read_csv("padres.csv"); names(padres) <-  columnNames
padres <- padres %>% mutate(Team="Padres") %>% filter(Year != 2019)

rockies <- read_csv("rockies.csv"); names(rockies) <-  columnNames
rockies <- rockies %>% mutate(Team="Rockies") %>% filter(Year != 2019)


data <- rbind(giants, db, dodgers, padres, rockies)
giants %>% arrange(Year)
db %>% arrange(Year)
dodgers %>% arrange(Year)
rockies %>% arrange(Year)
padres %>% arrange(Year)

```




## Matt

### Most Improved Award (1883 to 2018)

```{r}
# giants; db; dodgers; padres; rockies

CalculateImprovement <- function(df, teamName){
  df <- df %>% filter(Year==2018 | Year==1998)
  
  wins <- (df$Wins[1]/df$`Number of Games`[1]) - (df$Wins[2]/df$`Number of Games`[2])
  runsPerGame <- (df$`Runs per Game`[1]/df$`Number of Games`[1]) - (df$`Runs per Game`[2]/df$`Number of Games`[2])
  runsScored <- (df$`Runs scored`[1]/df$`Number of Games`[1]) - (df$`Runs scored`[2]/df$`Number of Games`[2])
  doubles <- (df$Doubles[1]/df$`Number of Games`[1]) - (df$Doubles[2]/df$`Number of Games`[2])
  tripples <-(df$Tripples[1]/df$`Number of Games`[1]) - (df$Tripples[2]/df$`Number of Games`[2])
  homeRuns <- (df$`Home runs`[1]/df$`Number of Games`[1]) - (df$`Home runs`[2]/df$`Number of Games`[2])
  errorsCommitted <- (df$`Errors committed`[1]/df$`Number of Games`[1]) - (df$`Errors committed`[2]/df$`Number of Games`[2])
  
  
# print(df$Wins[1]) 
# print(df$Wins[2])
# print(df$`Number of Games`)
  
  
# print(wins)
# print(runsPerGame)
# print(runsScored)
# print(doubles)
# print(tripples)
# print(homeRuns)
# print(errorsCommitted)
  

  improvement <- wins + runsPerGame + runsScored + doubles + tripples + homeRuns - errorsCommitted
  print(improvement)
  tb <- tribble(~Team, ~Improvement,
                teamName, improvement)
  return(tb)
  
}

 <- CalculateImprovement(db,  "Diamondbacks")
new
# new$Improvement
```

