---
title: "bing"
author: 'Blue Team: Matt Lawson,'
date: "3/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); library(knitr)
```


# How has the average tuition cost changed from 2004 to 2016

[This is where we got the dataset from.](https://github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-04-02)

[And this is where the dataset originally came from.](https://onlinembapage.com/average-tuition-and-educational-attainment-in-the-united-states/)


```{r, message=F}
df <- read_csv("us_avg_tuition.csv") %>%
  gather(key=Year, value=Cost, starts_with("20")) %>%
  arrange(State) 

df$Cost <- parse_number(df$Cost)
#kable(view(df))

ocean <- df %>% filter(State == "Washington" | State == "Oregon" | State == "California" | State == "Texas" | State == "Louisianna" | State == "Mississippi" | State == "Alabama" | State == "Florida" | State == "Georgia" | State == "South Carolina" | State == "North Carolina" | State == "Virginia" | State == "Maryland" | State == "Delaware" | State == "New Jersey" | State == "New York" | State == "Connecticut" | State == "Rhode Island" | State == "Massachussetts"| State == "New Hampshire" | State == "Maine" | State == "Hawaii" | State == "Alaska")

landLocked <- df %>% filter(!(State == "Washington" | State == "Oregon" | State == "California" | State == "Texas" | State == "Louisianna" | State == "Mississippi" | State == "Alabama" | State == "Florida" | State == "Georgia" | State == "South Carolina" | State == "North Carolina" | State == "Virginia" | State == "Maryland" | State == "Delaware" | State == "New Jersey" | State == "New York" | State == "Connecticut" | State == "Rhode Island" | State == "Massachussetts"| State == "New Hampshire" | State == "Maine" | State == "Hawaii" | State == "Alaska"))

#kable(view(ocean))
#kable(view(landLocked))

oceanSummary <- ocean %>%
  group_by(Year) %>%
  summarize(Average=mean(Cost), water = "yes")

llSummary <- landLocked %>%
  group_by(Year) %>%
  summarize(Average=mean(Cost), water = "no")



total <- bind_rows(oceanSummary, llSummary)
#kable(view(total))

ggplot(data = total) + geom_line(mapping = aes(x = Year, y = Average, group = water, color = water))

```