---
title: "Lab 8"
author: 'Blue Team: Matt Lawson,'
date: "3/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r, message=F}
df <- read_csv("us_avg_tuition.csv")

df <-df%>%
  gather(key=Year, value=Cost, starts_with("20")) %>%
  arrange(State) 

df$Cost <- parse_number(df$Cost)
head(df)
```
# How has the average tuition cost changed from 2004 to 2016

[This is where we got the dataset from.](https://github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-04-02)
[And this is where the dataset originally came from.](https://onlinembapage.com/average-tuition-and-educational-attainment-in-the-united-states/)

  <br><br> <br><br> <br><br>
#And the conclusion to the overall quesion goes here
<br><br> <br><br> <br><br>



#The team recomendation goes here and why its important to implement it
<br><br> <br><br> <br><br>


# A description of the dataset
<br><br> <br><br> <br><br>






# Individual Findings and Plots
  
#### Matt

__How does the least expensive state change throughout the years?__
<br><br>
```{r}
mattdf <- df %>%group_by(Year) %>%
  summarize(Cheapest = min(Cost), Expensive = max(Cost))

ggplot(mattdf) +
  geom_line(aes(x=Year, y=Cheapest, group=1), color="blue") +
  geom_line(aes(x=Year, y=Expensive, group=1), color="orange") + 
  labs(y="Cost", title="Most expensive and least expensive cost per year") 
  # scale_color_discrete(c("Least Expensive", "Most Expensive"))
```


#### Brandon
<br><br>


#### Nick
<br><br>


#### Bing
<br><br><br><br>




# Who Did what

##### Matt
<br><br>


##### Brandon
<br><br>


##### Nick
<br><br>


##### Bing