---
title: "Lab 12"
author: 'Blue Team: Matt Lawson,'
date: "4/10/2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse); library(gapminder)
```




```{r}
head(gapminder_unfiltered, 2)
# dim(gapminder_unfiltered)
data=gapminder_unfiltered
```


# Two-Sample Permutation Test

```{r}
perm_mean <- function(perms = 1000, values, n1) {
  output <- vector("double", length(perms))
  
  for (i in c(1:perms)) {
    A <- sample(values, n1)
    B <- setdiff(values, A)

    meanA <- mean(A)
    meanB <- mean(B)
    
    output[[i]] <- meanA - meanB
  }
  return(output)
}
```
  
```{r}
# set.seed(1)
diffs <- perm_mean(1000, data$lifeExp, 1000)
mean(diffs)
hist(diffs)
```





# Correlation Permuation Test


```{r}
perm_cor <- function(perms = 1000, x, y) {
  output <- vector("double", length(perms))
  
  for (i in c(1:perms)) {
    y <- sample(y)
    output[[i]] <- cor(x, y)
  }
  return(output)
}
```

```{r}
diffs <- perm_cor(1000, data$lifeExp, data$pop)
hist(diffs)
```

$\rho$ (the pearson correlation coeficient) is very close to 0, so we can assume that life expectancy and population are not coorelated.