---
title: "Lab 12"
author: "Blue Team: Nick Zimmerman, Matt Lawson, "
date: "4/12/2019"
output:
  html_document:
    df_print: paged
---



```{r include=FALSE}
library(tidyverse)
library(gapminder)
library(dbplyr)

perm_mean <- function(perms = 1000, values, n1){
  ## Variables ##
  # perms: The number of permutations 
  # values (num): 
  # n1 (int): Size of group 1
  ###############
  
  output <- vector("double", length(perms))
  
  # Loop throught number of permutations
  for (i in c(1:perms)){
    control <- sample(values,n1)
    test <- values[-control]
    
    control_mean <- mean(control)
    test_mean <- mean(test)
    
    output[[i]] <- control_mean - (control_mean - test_mean)/2 
  }
  
  return(enframe(output, name = NULL, value = "value"))
}


perm_cor <- function(perms = 1000, x, y){
  ## Variables ##
  # perms: The number of permutations 
  # x: Vector 1 - for computing correlation
  # y: Vector 2 - for computing correlation
  ###############
  
  output <- vector("double", length(perms))
  
  # Loop throught number of permutations
  for (i in c(1:perms))
  {
    # Randomly mix up the values in the vector "y"
    mix_y <- sample(y,length(y))
    
    # Compute the correlation between x and the randomly mixed
    # up y-vector. Store this value in the vector from step 1.
    output[[i]] <- cor(x,mix_y)
  }
  
  # Return new updated vector
  return(enframe(output, name = NULL, value = "value"))
}
```



### Nick

### Two sample permutation

Is there a difference in life expectancy between America and Australia?

```{r, warning=F, message=F}
set.seed(9999)
America_Australia <- filter(gapminder_unfiltered, country == "United States" | country == "Australia")
America_lifeExp <- filter(gapminder_unfiltered, country == "United States") %>% summarise(mean = mean(lifeExp))

ggplot(data = perm_mean(perms = 1000, America_Australia$lifeExp, 12)) +
  geom_histogram(mapping = aes(x = value),color="black", fill="white") +
  geom_vline(xintercept = America_lifeExp$mean, color="red", size=1.25)


```


### Corelation Permutation

Is there a relation between life expectancy and the disparaty between population and gdp?

```{r, warning=F, message=F}

gap_by_country <- gapminder_unfiltered %>% group_by(country) %>% summarise(lifeExp = mean(lifeExp), pop = mean(pop), gdpPercap = mean(gdpPercap))

ggplot(data = perm_cor(perms = 1000, gap_by_country$pop, gap_by_country$gdpPercap))+
  geom_histogram(mapping = aes(x = value),color="black", fill="white") + 
  labs(x="Correlation")

```

```{r}

gap_by_continent <- gapminder %>% group_by(continent) %>% summarise(lifeExp = mean(lifeExp), pop = mean(pop), gdpPercap = mean(gdpPercap))

ggplot(data = perm_cor(perms = 1000, gap_by_continent$pop, gap_by_continent$gdpPercap))+
  geom_density(mapping = aes(x = value))

ggplot(data = perm_cor(perms = 1000, gap_by_continent$lifeExp, gap_by_continent$gdpPercap))+
  geom_density(mapping = aes(x = value))

```

