---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
library(tidyverse)
milk <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/state_milk_production.csv')

milk <- milk %>%
  mutate(milk_million = milk_produced/1000000)

head(milk)
```


```{r}
milk %>%
  filter(year==1998) %>%
  ggplot(aes(x=milk_million)) +
  geom_histogram(bins=15) + 
  ggtitle("Distribution of milk production in 1998") + 
  labs(x="Million pounds of milk")
```

```{r}
byState <- milk %>%
  select(state, year, milk_million) %>%
  group_by(state) %>%
  filter(year==1998) %>%
  arrange(milk_million)

minState = byState$state[byState$milk_million == min(byState$milk_million)]
maxState = byState$state[byState$milk_million == max(byState$milk_million)]
medianState = byState$state[byState$milk_million == quantile(byState$milk_million, 0.5, type=1)]


info <- milk %>%
  group_by(year) %>%
  filter(year==1998) %>%
  summarise(mean = mean(milk_million), median=medianState, maximum=maxState, minimum=minState) 

info

```

```{r}
mostMilk <- milk %>%
  filter(year==2017) %>%
  arrange(desc(milk_million)) %>%
  top_n(5, milk_million)
mostMilk
```

```{r}
leastMilk <- milk %>%
  filter(year==2017) %>%
  arrange(milk_million) %>%
  top_n(-5, milk_million)
leastMilk
```


