---
title: "Lab 5"
author: "Blue Team: Matt Lawson, "
html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F, message=F}
library(tidyverse)
library(knitr)
milk <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/state_milk_production.csv')

milk <- milk %>%
  mutate(milk_million = milk_produced/1000000)
head(milk)
```

## Team Plots
```{r, message=F}
# yearAvg <- milk %>% group_by(year) %>% summarise(state = "All States", milk_million = mean(milk_million))

milksub <- milk %>%
  filter(state %in% c('California','Colorado','Oregon','Washington','Arizona', 'All States')) %>% select(state, year, milk_million)

# milksub

# milksub <- bind_rows(milksub, yearAvg)

averageByYear <- milk %>% 
  group_by(year) %>%
  summarize(average=mean(milk_million))

ggplot(data = milksub) +
  geom_point(mapping = aes(x= year, y = milk_million, color =state)) + 
  geom_smooth(data=averageByYear, aes(x=year, y=average), se=F, color="black")
```
### Year with the most milk produced
```{r}

```





### Year with the least milk produced
```{r}

```



### Top 5 Producers of Milk in 2017
```{r}
mostMilk <- milk %>%
  filter(year==2017) %>%
  arrange(desc(milk_million)) %>%
  top_n(5, milk_million) %>%
  select(state)
kable(mostMilk)
```



### Bottom 5 Producers of Milk in 2017
```{r}
leastMilk <- milk %>%
  filter(year==2017) %>%
  arrange(milk_million) %>%
  top_n(-5, milk_million) %>%
  select(state)
kable(leastMilk)
```

## Individual Plots

### Bing
```{r}
milk1998 <- milk %>%
  filter(year == 1998)

ggplot(data = milk1998, aes(x = milk_million)) + geom_histogram(bins = 10) + ggtitle('Histogram of milk produced in 1970 by state')
```
```{r}
t <- milk1998 %>% group_by(state) %>% summarise(average = mean(milk_million), med = median(milk_produced), max = max(milk_million), low = min(milk_million)) %>% as_tibble()
t
```


### Matt

```{r}
milk %>%
  filter(year==1998) %>%
  ggplot(aes(x=milk_million)) +
  geom_histogram(bins=15) + 
  ggtitle("Distribution of milk production in 1998") + 
  labs(x="Million pounds of milk")
```

```{r}
byState <- milk %>%
  select(state, year, milk_million) %>%
  group_by(state) %>%
  filter(year==1998) %>%
  arrange(milk_million)

minState = byState$state[byState$milk_million == min(byState$milk_million)]
maxState = byState$state[byState$milk_million == max(byState$milk_million)]
medianState = byState$state[byState$milk_million == quantile(byState$milk_million, 0.5, type=1)]


info <- milk %>%
  group_by(year) %>%
  filter(year==1998) %>%
  summarise(mean = mean(milk_million), median=medianState, maximum=maxState, minimum=minState) 

info
```

