---
title: "babies graph"
author: "Brandon Bowen"
date: "February 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
babies <- read_csv("https://raw.githubusercontent.com/ervance1/Sp2018-Data-Science-repo/master/babies2a.dat")
babies <- rename(babies, bwtoz = `bwt/oz`)
babies <- na.omit(babies)
```

```{r}
ggplot(data = babies, mapping = aes(x = as.factor(Premature), y = mpregwt, fill=as.factor(smoke))) + geom_boxplot() +
  scale_fill_discrete(name="smoking",
                      breaks=c(0,1),
                      labels=c("Non smoking", "Smoking")) +
  labs(x = "Premature")  +
  ggtitle("Does the mothers pre-pregnancy weight affect the chances of premature babies?")


```


```{r, echo = FALSE, warning = FALSE}
library(tidyverse)
library(dplyr)
babies <- read_csv("https://raw.githubusercontent.com/ervance1/Sp2018-Data-Science-repo/master/babies2a.dat")
babies <- rename(babies, bwtoz = `bwt/oz`)
head(babies)
ggplot(data=babies)+geom_bar(mapping = aes(x = smoke, y = ..prop.., fill = med)) + facet_grid(~med)


```


