---
title: "Lab 6"
author: "Blue Team: Matt Lawson, "
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
flights <- read_csv("https://files.osf.io/v1/resources/3z5as4pej8/providers/osfstorage/5a8ca28f57103100104584db")
```

```{r}
flights <- filter(flights, ORIGIN=="DEN" | DEST=="DEN")
flights <- mutate(flights,
  DAY_OF_WEEK = weekdays(as.Date(paste(flights$YEAR, flights$MONTH, flights$DAY_OF_MONTH, sep="-"))))
```


# Importance

```{r}
flights
```


# Results and Conclusions

```{r}

```


# Recomendation

```{r}

```


# Findings


### Matt
```{r}
days=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")

delays <- flights %>%
  filter(!is.na(CARRIER_DELAY)) %>%
  group_by(DAY_OF_WEEK) %>%
  summarize(Carrier=mean(CARRIER_DELAY),Weather=mean(WEATHER_DELAY), NAS=mean(NAS_DELAY), Security=mean(SECURITY_DELAY), Late_Arrival=mean(LATE_AIRCRAFT_DELAY)) %>%
  mutate(DAY_OF_WEEK = factor(DAY_OF_WEEK, levels = days)) %>%
  mutate("Total Delay" = Weather+NAS+Security+Late_Arrival) %>%
  arrange(DAY_OF_WEEK) 
delays
```
```{r}
melted <- melt(delays[,c('DAY_OF_WEEK', 'Carrier','Weather','NAS', 'Security', 'Late_Arrival')],id.vars = 1)

ggplot(melted, aes(x=DAY_OF_WEEK, y=value)) + 
  geom_bar(aes(fill=variable),width=.75, stat = 'identity', position=position_dodge()) + 
  labs(title="Average time of delay per day of the week", x="Day of the Week", y="Average delay time", fill="Type of delay")
```

This plot shows that weather and security delays are mostly constant throughout the week, but Carrier and Late Arrivals seem to vary.

```{r}
melted <- melt(delays[,c('DAY_OF_WEEK', 'Total Delay')],id.vars = 1)

ggplot(melted, aes(x=DAY_OF_WEEK, y=value)) + 
  geom_bar(stat = 'identity')
```

This plot shows that Friday and Monday have the most total delays thatn other days. 

# Who Did What